### ISSUE TITLE
SoC AssertionError in generate_from_simbev.py

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/spice_ev#1]
Hey @stefansc1,

I was happy to see that you have some plausibility checks implemented for the simulation based upon simBEV data in `generate_from_simbev.py`. I just stumbled across an AssertionError that I'd like to hear your opinion about:

```python
Traceback (most recent call last):
  File "generate_from_simbev.py", line 257, in <module>
    assert simbev_soc_start > 0 and simbev_soc_end > 0, \
AssertionError: SimBEV created negative SoC for phev_luxury_00000_standing_t in row 61
```

In these lines
https://github.com/rl-institut/spice_ev/blob/416fb6d9e9dddd0cce8e85e2234c8cba9dde1ba5/generate_from_simbev.py#L257-L259
you check the SoCs which gives an assertion error for a simBEV csv line such as

|     | car_type    | bat_cap | location | netto_charging_capacity | SoC_start | SoC_end | chargingdemand | charge_time | park_start | park_end | drive_start | drive_end | consumption        |
|-----|-------------|---------|----------|-------------------------|-----------|---------|----------------|-------------|------------|----------|-------------|-----------|--------------------|
| ... | ...         | ...     | ...      | ...                     | ...       | ...     | ...            | ...         | ...        | ...      | ...         | ...       |                    |
| 59  | phev_luxury | 40      | driving  | 0.0                     | 1.0       | 0.0     | 0.0            | 0           | 0          | 0        | 937         | 956       | 106.20382399999998 |
| ... | ...         | ...     | ...      | ...                     | ...       | ...     | ...            | ...         | ...        | ...      | ...         | ...       |                    |

since `SoC_end`=0. Althought the consumption seems to be flawed (cf. https://github.com/rl-institut/simbev/issues/26) it is realistic to have a fully discharged EV after a trip, right?
So shouldn't the SoC should rather checked with `simbev_soc_start >= 0 and simbev_soc_end >= 0`?

**Comment by stefansc1** [comment]
This was a design decision. I wanted to avoid scenarios where the car rolls up to the charging station with a completely dry battery. Realistically, you would want to charge when reaching a certain threshold, e.g., 10% or 20%. As a compromise, I would suggest values below 0 are rejected, values above 0 but below a certain (configurable?) threshold generate a warning.

**Comment by nesnoj** [comment]
> This was a design decision. I wanted to avoid scenarios where the car rolls up to the charging station with a completely dry battery. Realistically, you would want to charge when reaching a certain threshold, e.g., 10% or 20%.

That's true, but I'd like not to hamper the use of spiceEV by this restriction...

> As a compromise, I would suggest values below 0 are rejected, values above 0 but below a certain (configurable?) threshold generate a warning.

Sounds good to me! I made a proposal in #3 (currently without a threshold, add some if you like)

**Comment by nesnoj** [comment]
Thanks for the quick solution @stefansc1 !
