### ISSUE TITLE
SoC AssertionError due to identical EV names

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/spice_ev#10]
Like in #6, non-unique EV file names lead to wrong lookup(s) in
https://github.com/rl-institut/spice_ev/blob/025afb80cf9be1d4785c82fe12523f60b4087ef2/src/strategy.py#L84-L87
and subsequently to wrong SoC calculation.
Is this as easy to fix as in #6 @stefansc1 ?

If you need an example file to test, here is one created from 2 simBEV files with the same name (as usual, remove txt extension):
[x.json.TXT](https://github.com/rl-institut/spice_ev/files/6637184/x.json.TXT)

Alternative solution would be to make simBEV filenames unique..

**Comment by stefansc1** [comment]
Ah yes, just waited for it. Have a look at the new dev branch, should be fixed with cd2e7b2c9ffbdd9d3485f480319f6617dece479b

**Comment by nesnoj** [comment]
I'll start my run with many cars..

**Comment by nesnoj** [comment]
Seems to work out at first sight, but something else went wrong, gotta check...
BTW: I added a rename warning in 15735e1ff33fd351acd00f6ad58d6e221b52ffec
