### ISSUE TITLE
Adapt spiceEV to use simBEV's new output format and metadata to parametrize generate_from_simbev.py

### ISSUE THREAD

**Issue by nesnoj** [rl-institut/spice_ev#11]
As soon as there's a meta dataset (https://github.com/rl-institut/simbev/issues/27) for a run

- [ ] Use the vehicle data to parametrize `generate_from_simbev.py`: `vehicle_types` [here](https://github.com/rl-institut/spice_ev/blob/ffb9662a3fc95018b543d7b118e33f3ab3e1d324/generate_from_simbev.py#L65-L108) including `battery_efficiency` for each vehicle (side note: default set in ffb9662a3fc95018b543d7b118e33f3ab3e1d324)
- [ ] Other values as listed in https://github.com/rl-institut/simbev/issues/27

**Comment by nesnoj** [comment]
simBEV [v0.1.2](https://github.com/rl-institut/simbev/releases/tag/v0.1.2) has been released with
- a changed output format
- metadata are now exported https://github.com/rl-institut/simbev/issues/27

spiceEV needs to be adapted accordingly.

**Comment by mosc5** [comment]
SimBEV [v1.0.0](https://github.com/rl-institut/simbev/tree/v1.0.0) has been released with

- a changed output format
