### ISSUE TITLE
feature: generate skript for fleets (bus trips)

### ISSUE THREAD

**Issue by Piranias** [rl-institut/spice_ev#40]
The goal is to read in a csv file for all rotations with each line containing a trip and convert the trips to arrival and departure events. 

Alternative: read in a json of the format:

{rotations_id: {
distance_rotation, 
departure time,
arrival time,
vehicle_type,
charging_type,
trips: { 
trip1, ...}
}  
}

note: 
* the vehicle events need to contain information about the rotation_id
* pro json: the charging type could directly be determined by the distance_rotation (energy consumption beeing calculated before).
* the grid connector need to be set according to the end station ( so grid_connector = end_station_name )

**question @stefansc1:**
does it make sense to create arrival/departure events for bus stations (Zwischenhaltestellen) that are not electrified (so no charging could happen here). One easy workaround to disable charging would be to set the desired_soc == soc at the arrival event.  What do you think?

Another way would be to sum up all trips between two electrified end stations in a preprocessing. Allthough this way the information about the trips would get lost, which would not be ideal (and maybe important for output @paulboehnke @j-brendel .

**Comment by stefansc1** [comment]
Regarding the intermediate non-electrified stops: I would suggest to set `connected_charging_station` to None/null. Currently, there is a check in strategy.py that the connected charging station is set, this should be removed (not sure why it's there, all strategies should check that the vehicle that is trying to charge is properly connected).
