### ISSUE TITLE
v2g in flex_window: 'Battery' object has no attribute 'charging_curve'

### ISSUE THREAD

**Issue by jakobgemassmer** [rl-institut/spice_ev#45]
In the strategy flex_window the v2g-capability doesn't work properly. Simulation aborts directly with the AttributeError: 'Battery' object has no attribute 'charging_curve'

Problem appears with all load_strats "balanced", "needy" and "greedy"

[test.json.txt](https://github.com/rl-institut/spice_ev/files/7717210/test.json.txt)
[schedule_NSM_5.csv](https://github.com/rl-institut/spice_ev/files/7717227/schedule_NSM_5.csv)

**Comment by jakobgemassmer** [comment]
[schedule_NSM_5.csv](https://github.com/rl-institut/spice_ev/files/7717224/schedule_NSM_5.csv)

**Comment by paulboehnke** [comment]
Fixed. I got confused with the namings. 
FYI Simulation still does not finish when running your scenario with NSM_07. Exits with a vehicle not charged sufficiently.
