### ISSUE TITLE
flex_window exceeding power at grid connector

### ISSUE THREAD

**Issue by jakobgemassmer** [rl-institut/spice_ev#53]
With the strategy flex_window charging should happen when the "charge"-timeseries in the schedule.csv shows a 1 and less (or better no charging) should happen when it shows a 0. Hard limits are of course reaching the desired_soc and not exceeding the grid connector power.
The strategy works fine if the grid connector allows enough charging in timesteps with a "1". Both with and without v2g. GC is set to 40 kW.
![fw_correct](https://user-images.githubusercontent.com/49757031/149741365-a2c1cc8d-3da3-4642-96a8-1106cf6bbe7f.png)

However, flex_window shows several cases, in which the power at the grid connector is exceeded:
1. Power at GC is exceeded in a charge-window ("1"). In this example the GC is set to 12.5 kW:
![fw_12,5](https://user-images.githubusercontent.com/49757031/149740672-bd0d80e0-a136-409c-a32e-618ee477c352.png)
 
2. GC is exceeded in a no-charge-window ("0") and a charge-window. GC is set to 10 kW.
![fw](https://user-images.githubusercontent.com/49757031/149741607-5beb4084-2306-4313-99ad-25f78788a666.png)

The simulation doesn't fail because margin=1. But in every case, the GC must not be exceeded!

**Comment by paulboehnke** [comment]
#55

**Comment by jakobgemassmer** [comment]
Fixed in merged PR #55
