### ISSUE TITLE
GC exceeded in schedule when using Battery and strat_option "balanced_vehicle"

### ISSUE THREAD

**Issue by jakobgemassmer** [rl-institut/spice_ev#65]
When using a battery, the GC is exceeded in strategy schedule with the sub-strategy "balanced_vehicle".
In the example GC is set to 30 kW, however max_power = 30.53571428571427 kW

strategy_option = [["LOAD_STRAT", "balanced_vehicle"]]
margin = 1
![grafik](https://user-images.githubusercontent.com/49757031/150875184-9a9df5cf-8b1f-4bb6-b924-80060984449b.png)

[dhl_schedule.json.txt](https://github.com/rl-institut/spice_ev/files/7925606/dhl_schedule.json.txt)
[dhl_schedule_nobat.json.txt](https://github.com/rl-institut/spice_ev/files/7926792/dhl_schedule_nobat.json.txt)
[dhl.csv](https://github.com/rl-institut/spice_ev/files/7925607/dhl.csv)

**Comment by paulboehnke** [comment]
Adressed in #60. 

Stationary battery efficiency was neglected when charging vehicles from battery. 
Added a reality check in every step to make sure only as much energy from stationary battery is allocated to vehicles as is actually available.

**Comment by stefansc1** [comment]
fixed in #60
