### ISSUE TITLE
BusTool: Info about priorization

### ISSUE THREAD

**Issue by Piranias** [rl-institut/spice_ev#85]
FYI: In case that the number of charging stations at the depot (loading strategy balanced) is restricted, eg. only one cs is available at a time, the first car tries to load balanced within its standing time, therefore the second car might have to load with full power because there is not enough time left. This is no problem for the BusTool right now, because we only have restricted number of cs at the opp stations and the loading strategy is greedy there. Still, one could keep that in mind for future enhancements.

Here's an example with two cars having the exact same schedule but only one cs at a time available:
![priorization](https://user-images.githubusercontent.com/44803304/156145441-2936e782-145d-4226-ac86-30ab62f43f03.png)

**Comment by jakobgemassmer** [comment]
@j-brendel is this still an issue? Otherwise I would close this SpiceEV issue!

**Comment by j-brendel** [comment]
It is good to know, but the issue can be closed.
