### ISSUE TITLE
generate_from_csv: adjust min_standing_time

### ISSUE THREAD

**Issue by Piranias** [rl-institut/spice_ev#90]
The min_standing_time is a fixed value now. I thought about adding a feature that calculates the min_standing_time from the vehicle battery capacity and the charging power. We could then assume that there needs to be enough time to load the vehicle at least e.g. 80% of it's soc. This might just work for a constant loading curve though. @jakobgemassmer ,what do you think?  

this is relevant for generate_from_csv.py and the bus_tool

**Comment by jakobgemassmer** [comment]
I think the feature makes sense, but the question is "what is the reason for min_standing_time?"
Time for cleaning/loading etc. or time for little recharging? However I think this could be added at a later stage.

**Comment by Piranias** [comment]
The min_standing_time (at depot) is very significant, because it sets the time for a vehicle to fully charge at the depot. If it is set to None / 0 the vehicles are assigned first in first out, so it might happen that a vehicle does another trip / rotation even though it has not been fully charged. The method above should help to define this time needed to fully charge (or at least load up to 80%)

**Comment by Piranias** [comment]
new idea:
sum up consumption of all previous trips since last connect_cs = 1.

`standing_time_deps_depb = sum_consumption / cs_power`

**Comment by jakobgemassmer** [comment]
Would `recharge_fraction` then be the same as `min_soc`?

**Comment by Piranias** [comment]
No, he recharge fraction is just the fraction of the capacity that should be recharged. It does not say anything about the actual SoC of the vehicle at the time leaving. 

One example:
capacity = 400 kWh
recharge fraction = 0.5
cs_power = 100 kW
-> the vehicle stands for at least 2 hours to recharge 200 kW.

If the vehicle comes in with an SoC of 0.1, this would mean it would leave with soc 0.6, if it comes in with 0.5 it would leave with SoC of 1

**Comment by Piranias** [comment]
Ok, I understand your point. Making it the same as min_soc would ensure that min_soc can be reached. Bus is this always the case? Maybe one wants to give the vehicles more time to load (recharge_fraction = 1), so that the vehicles do not need the full cs_power, even though min_soc = 0.8? So the question is just, if we want another variable or only the min_soc.

**Comment by jakobgemassmer** [comment]
You are right, another variable seems reasonable.
